services:
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/data
    ports:
      - 3200:3200
      - 4418:4418
    command: ["-config.file=/etc/tempo.yaml"]
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
  app:
    container_name: app
    image: golang:1.24.2-alpine3.21
    ports:
      - 6000:6000
    volumes:
      - ./app:/app
    command: /bin/sh -c "chmod +x /app/run.sh && /app/run.sh"
    environment:
      - OTLP_ENDPOINT=192.168.254.127:4418
